name: Deploy to GCP

on: 
  push: 
    branches:
      - "develop"
      
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
            project_id: ${{ secrets.GCP_PROJECT }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            export_default_credentials: true     
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Build image
        working-directory: ./node-app
        run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/node-app
      - name: Deploy container
        working-directory: ./node-app
        run: gcloud run deploy node-app --image gcr.io/${{ secrets.GCP_PROJECT }}/node-app --region=${{ secrets.GCP_REGION }}